version: '3.9'

services:
  mongo1:
    image: mongo:5
    container_name: mongo1
    networks:
      - mongoCluster
    ports:
      - "27017:27017"
    volumes:
      - mongo1-data:/data/db
    command: ["mongod", "--replSet", "rs0"]
    restart: unless-stopped

  mongo2:
    image: mongo:5
    container_name: mongo2
    networks:
      - mongoCluster
    ports:
      - "27018:27017"
    volumes:
      - mongo2-data:/data/db
    command: ["mongod", "--replSet", "rs0"]
    restart: unless-stopped

  mongo3:
    image: mongo:5
    container_name: mongo3
    networks:
      - mongoCluster
    ports:
      - "27019:27017"
    volumes:
      - mongo3-data:/data/db
    command: ["mongod", "--replSet", "rs0"]
    restart: unless-stopped

  init-replica:
    image: mongo:5
    container_name: init-replica
    networks:
      - mongoCluster
    volumes:
      - ./DB-setup/init-replica.js:/init-replica.js
      - ./DB-setup/init-db.js:/init-db.js
      - ./DB-setup/setup-replica.sh:/setup-replica.sh
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    command: ["bash", "-c", "/setup-replica.sh"]
    restart: "no"

  yolo5:
      build: ./yolo5
      container_name: yolo5
      ports:
        - "8081:8081"
      environment:
        BUCKET_NAME: fnaarani-bucket
      networks:
        - mongoCluster

networks:
  mongoCluster:
    driver: bridge

volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data:
